// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZnkKnVguE9GhTuc7YI6WVwZZ0UP0JgkY',
    appId: '1:665775063562:web:f1df47b3a4e2310809d5f3',
    messagingSenderId: '665775063562',
    projectId: 'dynamicthemingplatform',
    authDomain: 'dynamicthemingplatform.firebaseapp.com',
    storageBucket: 'dynamicthemingplatform.appspot.com',
    measurementId: 'G-RCCGWDBRFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_abcdefgh',  // Replace with actual Android API Key if needed
    appId: '1:665775063562:android:b301c0290e50ddaf09d5f3',
    messagingSenderId: '665775063562',
    projectId: 'dynamicthemingplatform',
    storageBucket: 'dynamicthemingplatform.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_ijklmnop',  // Replace with actual iOS API Key if needed
    appId: '1:665775063562:ios:609a32bc6e5966fc09d5f3',
    messagingSenderId: '665775063562',
    projectId: 'dynamicthemingplatform',
    storageBucket: 'dynamicthemingplatform.appspot.com',
    iosClientId: '665775063562-abcde1234.apps.googleusercontent.com',
    iosBundleId: 'com.claysol.dynamicthemeexample.example',
  );
}